install.packages('NLP')
install.packages('slam')
install.packages("tm", repos="http://R-Forge.R-project.org")
install.packages("RSQLite")
install.packages("wordcloud")
install.packages('kableExtra')
install.packages('gridExtra')
install.packages('stats')
install.packages('DT')
install.packages('treemap')
install.packages("stringr")
install.packages('pandoc')
